version: '3.9'

services:
  db:
    image: mysql
    container_name: ucalendardb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Bucharest
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
    volumes:
      - ucalendar:/var/lib/mysql
volumes:
  ucalendar:
 