sequenceDiagram
  participant Calendar
  actor User

  User ->> Calendar: Visit dedicated page
  User ->> Calendar: Inspect monthly overview
  User ->> Calendar: Inspect weekly overview
  User ->> Calendar: Click date
  User ->> Calendar: Inspect detailed tasks